/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package net.birdirbir.admobrewarded;

import java.util.HashMap;

import net.birdirbir.admobrewarded.RewardedVideoProxy;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;

import android.content.Context;

import com.google.android.gms.ads.MobileAds;
import com.google.android.gms.ads.reward.RewardedVideoAd;
import com.google.android.gms.common.GoogleApiAvailability;

@Kroll.module(name = "Admob", id = "net.birdirbir.admobrewarded")
public class AdmobrewardedModule extends KrollModule {

	// Standard Debugging variables
	static final String LCAT = "AdmobModule";
	private static RewardedVideoProxy instance = null;

	@Kroll.constant
	public static final String AD_REWARDED = "ad_rewarded";
	@Kroll.constant
	public static final String AD_REWARDED_VIDEO_LEFT_APPLICATION = "ad_rewarded_left_app";
	@Kroll.constant
	public static final String AD_REWARDED_VIDEO_AD_CLOSED = "ad_rewarded_ad_closed";
	@Kroll.constant
	public static final String AD_REWARDED_VIDEO_FAILED_TO_LOAD = "ad_rewarded_failed_to_load";
	@Kroll.constant
	public static final String AD_REWARDED_VIDEO_AD_LOADED = "ad_rewarded_video_ad_loaded";
	@Kroll.constant
	public static final String AD_REWARDED_VIDEO_AD_OPENED = "ad_rewarded_video_ad_opened";
	@Kroll.constant
	public static final String AD_REWARDED_VIDEO_STARTED = "ad_rewarded_video_started";

	public AdmobrewardedModule() {
		super();
	}

	@Kroll.method
	public int isGooglePlayServicesAvailable() {
		return GoogleApiAvailability.getInstance()
				.isGooglePlayServicesAvailable(
						TiApplication.getAppCurrentActivity().getApplication()
								.getApplicationContext());
	}

	@Kroll.method(runOnUiThread = true)
	public RewardedVideoProxy createAd(@SuppressWarnings("rawtypes") HashMap hm) {
		@SuppressWarnings("unchecked")
		KrollDict args = new KrollDict(hm);
		String adUnitID = args.getString("adUnitID");
		Log.d(LCAT, "enter getRewardedVideoAdInstance");
		if (instance == null) {
			Log.d(LCAT, "creating new rewarded video instance");
			instance = new RewardedVideoProxy();
			Context context = TiApplication.getAppCurrentActivity()
					.getApplication().getApplicationContext();
			MobileAds.initialize(context, adUnitID);
			RewardedVideoAd r = MobileAds.getRewardedVideoAdInstance(context);
			instance.setAdUnitId(adUnitID);
			instance.setAd(r);
			instance.setContext(context);
			r.setRewardedVideoAdListener(instance);
		}
		return instance;
	}
}
